/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.matafe.docker;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class AppTest {

	App classUnderTest;

	@BeforeEach
	public void before() {
		this.classUnderTest = new App();
	}

	@Test
	public void testSomeLibraryMethod() {
		assertEquals("Hello World Docker", classUnderTest.getMessage());
	}
}
